services:
  # --- Service 1 : La Base de données ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iot_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3310:3306"
    # AJOUT 1 : Le Healthcheck
    # Docker va vérifier toutes les 5s si MySQL répond au "ping"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- Service 2 : L'API ---
  api:
    build: ./api
    container_name: projet-2026-api
    restart: always
    ports:
      - "127.0.0.1:3005:3000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=iot_project
      - HIVEMQ_HOST=8487c77b02c844dbb8bf01681e09f417.s1.eu.hivemq.cloud
      - HIVEMQ_USER=etudiant
      - HIVEMQ_PASS=Api_client2026
    # AJOUT 2 : Condition de démarrage
    depends_on:
      db:
        condition: service_healthy # L'API attendra que la DB soit "healthy" (prête)
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  # --- Service 3 : Le Dashboard (Frontend) ---
  dashboard:
    build: ./dashboard
    restart: always
    ports:
      # Idem pour le dashboard : seul Nginx pourra le servir sur le port 443
      - "127.0.0.1:8085:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html

volumes:
  db_data: