services:
  # --- Service 1 : La Base de données ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iot_project
      MYSQL_USER: user        # L'utilisateur créé
      MYSQL_PASSWORD: password # Le mot de passe associé
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3310:3306" # Ports INCHANGÉS
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- Service 2 : L'API ---
  api:
    build: ./api
    container_name: projet-2026-api
    restart: always
    ports:
      - "127.0.0.1:3005:3000" # Ports INCHANGÉS
    environment:
      # SURCHARGE POUR DOCKER (Prioritaire sur le .env)
      - DB_HOST=db
      - DB_PORT=3306
      # RÉCUPÉRATION DES VARIABLES DU .ENV
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - HIVEMQ_HOST=${HIVEMQ_HOST}
      - HIVEMQ_USER=${HIVEMQ_USER}
      - HIVEMQ_PASS=${HIVEMQ_PASS}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  # --- Service 3 : Le Dashboard ---
  dashboard:
    build: ./dashboard
    restart: always
    ports:
      - "127.0.0.1:8085:80" # Ports INCHANGÉS
    volumes:
      - ./dashboard:/usr/share/nginx/html

volumes:
  db_data: